version: '2'
services:
  zookeeper:
    #image: wurstmeister/zookeeper
    #image: confluentinc/cp-zookeepe
    #ports:
    #  - "2181:2181"
    image: confluentinc/cp-zookeeper:5.4.3
    #restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      #ZOOKEEPER_SERVERS: "zookeeper:22888:23888"
    ports:
      - "2181:2181"
  kafka:
    #image: wurstmeister/kafka
    image: confluentinc/cp-kafka:5.4.3
    depends_on:
      - zookeeper
    ports:
    # - "29092:29092"
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      #KAFKA_LISTENERS: LISTENER_FRED://localhost/127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
     # KAFKA_BROKER_ID: 1
     # KAFKA_BROKER_RACK: "r1"
    #  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     # KAFKA_DELETE_TOPIC_ENABLE: "true"
     # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      #KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8081"
      #KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
     # KAFKA_JMX_PORT: 9991

